package betterview;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Rogier on 20-11-15
 */
public class GridView {
    private JPanel panel1;
    private WhiteSquare whitesquare19;
    private BlackSquare blacksquare09;
    private WhiteSquare whitesquare08;
    private WhiteSquare whitesquare06;
    private WhiteSquare whitesquare04;
    private WhiteSquare whitesquare02;
    private WhiteSquare whitesquare00;
    private WhiteSquare whitesquare17;
    private WhiteSquare whitesquare15;
    private WhiteSquare whitesquare13;
    private WhiteSquare whitesquare11;
    private BlackSquare blacksquare07;
    private BlackSquare blacksquare05;
    private BlackSquare blacksquare03;
    private BlackSquare blacksquare01;
    private BlackSquare blacksquare18;
    private BlackSquare blacksquare16;
    private BlackSquare blacksquare14;
    private BlackSquare blacksquare12;
    private BlackSquare blacksquare10;
    private WhiteSquare whitesquare28;
    private WhiteSquare whitesquare26;
    private WhiteSquare whitesquare24;
    private WhiteSquare whitesquare22;
    private WhiteSquare whitesquare20;
    private WhiteSquare whitesquare39;
    private WhiteSquare whitesquare37;
    private WhiteSquare whitesquare35;
    private WhiteSquare whitesquare33;
    private WhiteSquare whitesquare31;
    private WhiteSquare whitesquare48;
    private WhiteSquare whitesquare46;
    private WhiteSquare whitesquare44;
    private WhiteSquare whitesquare42;
    private WhiteSquare whitesquare40;
    private WhiteSquare whitesquare59;
    private WhiteSquare whitesquare57;
    private WhiteSquare whitesquare55;
    private WhiteSquare whitesquare53;
    private WhiteSquare whitesquare51;
    private WhiteSquare whitesquare68;
    private WhiteSquare whitesquare66;
    private WhiteSquare whitesquare64;
    private WhiteSquare whitesquare62;
    private WhiteSquare whitesquare60;
    private WhiteSquare whitesquare79;
    private WhiteSquare whitesquare77;
    private WhiteSquare whitesquare75;
    private WhiteSquare whitesquare73;
    private WhiteSquare whitesquare71;
    private WhiteSquare whitesquare88;
    private WhiteSquare whitesquare86;
    private WhiteSquare whitesquare84;
    private WhiteSquare whitesquare82;
    private WhiteSquare whitesquare80;
    private WhiteSquare whitesquare99;
    private WhiteSquare whitesquare97;
    private WhiteSquare whitesquare95;
    private WhiteSquare whitesquare93;
    private WhiteSquare whitesquare91;
    private BlackSquare blacksquare29;
    private BlackSquare blacksquare27;
    private BlackSquare blacksquare25;
    private BlackSquare blacksquare23;
    private BlackSquare blacksquare21;
    private BlackSquare blacksquare38;
    private BlackSquare blacksquare36;
    private BlackSquare blacksquare34;
    private BlackSquare blacksquare32;
    private BlackSquare blacksquare30;
    private BlackSquare blacksquare49;
    private BlackSquare blacksquare47;
    private BlackSquare blacksquare45;
    private BlackSquare blacksquare43;
    private BlackSquare blacksquare41;
    private BlackSquare blacksquare58;
    private BlackSquare blacksquare56;
    private BlackSquare blacksquare54;
    private BlackSquare blacksquare52;
    private BlackSquare blacksquare50;
    private BlackSquare blacksquare69;
    private BlackSquare blacksquare67;
    private BlackSquare blacksquare65;
    private BlackSquare blacksquare63;
    private BlackSquare blacksquare61;
    private BlackSquare blacksquare78;
    private BlackSquare blacksquare76;
    private BlackSquare blacksquare74;
    private BlackSquare blacksquare72;
    private BlackSquare blacksquare70;
    private BlackSquare blacksquare89;
    private BlackSquare blacksquare87;
    private BlackSquare blacksquare85;
    private BlackSquare blacksquare83;
    private BlackSquare blacksquare81;
    private BlackSquare blacksquare98;
    private BlackSquare blacksquare96;
    private BlackSquare blacksquare94;
    private BlackSquare blacksquare92;
    private BlackSquare blacksquare90;


}
